site_name: Bases estatísticas SES
site_author: Thiago Holanda
site_description: >-
  Documentação do projeto

theme:
  name: material
  logo: assets/logo_susep.png

  palette:
    - scheme: default
      primary: black      
      toggle:
        icon: material/weather-sunny
        name: Modo Claro

    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Modo dark
    
    - scheme: solarized
      primary_dark: green
      accent : blue
      toggle:
        icon: material/weather-night-partly-cloudy
        name: Light mode
    
     

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    home: home


  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
   # - content.code.select
   # - content.footnote.tooltips
   # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  
  extra:
    toc_title: "Meu Conteúdo"

plugins:
  - search
  #  separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings
  - mermaid2:
      version: 10.0.2



markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde      

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    #- icon: fontawesome/brands/youtube
    #  link: https://www.youtube.com/@arrudaconsulting
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thr0/



watch:
  - docs

nav:
  - Home: index.md
  - Funcões: funcoes.md
  - Contratos de dados:
    - Arquivos:
      - Ses_cias.csv: schemas/schema_SesCias.md
      - Ses_ramos.csv: schemas/schema_SesRamos.md
      - Ses_gruposramos.csv: schemas/schema_SesGrupoRamo.md
      - Ses_seguros.csv: schemas/schema_SesSeguros.md
      - Ses_uf2.csv: schemas/schema_SesUf2.md
      - Ses_campos.csv: schemas/schema_SesCampos.md
      - Ses_Balanco.csv: schemas/schema_SesBalanco.md
      - Ses_Dados_Cap.csv: schemas/schema_SesDadosCap.md
      - Ses_Cap_UF.csv: schemas/schema_SesCapUf.md
      - Ses_ValoresMovRamos.csv: schemas/schema_SesValoresMovRamos.md
      - Ses_Valoresresmovgrupos.csv: schemas/schema_SesMovGrupos.md